image: cirrusci/flutter:stable

stages:
  - test
  - build

before_script:
  - flutter pub get

analiz_ve_test:
  stage: test
  script:
    - flutter analyze
    - flutter test
  only:
    - master
    - develop
    - merge_requests

android_build:
  stage: build
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
  only:
    - master
    - tags

ios_build:
  stage: build
  script:
    - flutter build ios --release --no-codesign
  artifacts:
    paths:
      - build/ios/iphoneos
  only:
    - master
    - tags 